sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated -o Dpkg::Options::="--force-confnew" docker-ce
  - sudo apt-get install -y --allow-unauthenticated sshpass software-properties-common python-software-properties
    # software-properties-common for ubuntu 14.04
    # python-software-properties for ubuntu 12.04

install:
  - sudo pip install docker
  - sudo pip install ansible
  - ansible --version
  - ansible-galaxy install -v -f -r tests/requirements.yml


script:
  - ansible-playbook -i tests/inventory-centos tests/playbook.yml --syntax-check
  - ansible-playbook -i tests/inventory-centos tests/playbook.yml --list-tasks
  - ansible-playbook -i tests/inventory-centos tests/playbook.yml --connection=local --become
  - 'ansible-playbook -i tests/inventory-centos tests/playbook.yml --connection=local --become | grep -q "changed=0.*failed=0" &&
    (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'

after_script:
  - ansible-playbook -i tests/inventory-centos tests/playbook_delete_containers.yml --connection=local --become

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
