---
- name: Find JumpCloud agent config to determine whether JumpCloud is installed
  ansible.builtin.stat:
    path: "{{ jumpcloud_agent_config }}"
  register: jumpcloud_agent_config_status

- name: Set whether JumpCloud is already installed
  ansible.builtin.set_fact:
    jumpcloud_is_installed: >-
      {{
        jumpcloud_agent_config_status.stat.isreg is defined
        and jumpcloud_agent_config_status.stat.isreg
      }}

- name: Report JumpCloud install state
  ansible.builtin.debug:
    msg: "Is JumpCloud installed: {{ jumpcloud_is_installed }}"
  when: debug | default(false) | bool
