---
- name: Read JumpCloud agent config
  ansible.builtin.slurp:
    src: "{{ jumpcloud_agent_config }}"
  register: jumpcloud_agent_config_content
  become: "{{ jumpcloud_use_sudo }}"
  no_log: true

- name: Set JumpCloud system key
  ansible.builtin.set_fact:
    jumpcloud_system_key: >-
      {{
        (
          jumpcloud_agent_config_content.content
          | b64decode
          | from_json
        ).systemKey
      }}
  no_log: true
