---
- name: Download JumpCloud kickstart script
  ansible.builtin.get_url:
    url: "{{ jumpcloud_x_connect_url }}"
    dest: "{{ jumpcloud_kickstart_script }}"
    mode: "0755"
    headers:
      x-connect-key: "{{ jumpcloud_x_connect_key }}"
  become: "{{ jumpcloud_use_sudo }}"
  no_log: true

- name: Install JumpCloud agent
  ansible.builtin.command: >-
    /usr/bin/env timeout
    {{ jumpcloud_install_timeout_seconds | int }}
    /bin/bash
    {{ jumpcloud_kickstart_script }}
  args:
    creates: "{{ jumpcloud_agent_config }}"
  become: "{{ jumpcloud_use_sudo }}"
  register: jumpcloud_install_result
  changed_when: jumpcloud_install_result.rc == 0

- name: Check JumpCloud agent config again
  ansible.builtin.stat:
    path: "{{ jumpcloud_agent_config }}"
  register: jumpcloud_agent_config_status
  become: "{{ jumpcloud_use_sudo }}"

- name: Report JumpCloud agent config status
  ansible.builtin.debug:
    var: jumpcloud_agent_config_status
  when: debug | default(false) | bool

- name: Check again if JumpCloud has been initialized
  ansible.builtin.set_fact:
    jumpcloud_is_installed: >-
      {{
        jumpcloud_agent_config_status.stat.isreg is defined
        and jumpcloud_agent_config_status.stat.isreg
      }}

- name: Reset JumpCloud if jcagent.conf has not been created
  ansible.builtin.import_tasks: reset_jumpcloud.yml
  when: not jumpcloud_is_installed
